GET http://localhost:8080/recap/api/info

###
POST http://localhost:8080/recap/api/login
Content-Type: application/json

{
  "username": "admin",
  "password": "test123"
}
###
GET http://localhost:8080/recap/api/info/xxx
x-access-token:eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTY4MTMwMDE2NSwiaWF0IjoxNjgxMjk4MzY1LCJpc3N1ZXIiOiJzZW1lc3RlcnN0YXJ0Y29kZS1kYXQzIiwicm9sZXMiOiJhZG1pbiIsInVzZXJuYW1lIjoiYWRtaW4ifQ.UoaEd2U2X2Lbt71BFIuuFZ8igY26Zuf2IqJlOY-tGVU

