POST http://localhost:8080/devops_starter_war_exploded/api/login

{
"username":"user",
"password": "test123"
}

###
GET http://localhost:8080/devops_starter_war_exploded/api/info/user
x-access-token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyIiwicm9sZXMiOiJ1c2VyIiwiZXhwIjoxNjQ5MTUzNjk1LCJpYXQiOjE2NDkxNTE4OTUsImlzc3VlciI6InNlbWVzdGVyc3RhcnRjb2RlLWRhdDMiLCJ1c2VybmFtZSI6InVzZXIifQ.M37mbUbtmYz4usOUTQNujFzYaWMm3GZjVyzFgulPRgU